### ISSUE TITLE
download_csv from yahoofinance erreur

### ISSUE THREAD

**Issue by hmz123** [gbeced/pyalgotrade#102] opened 2017-07-27 10:15 UTC
Hi Guys,
i have a problem with download_csv with yahoo finance with the New API
someone can help me  ?

**Comment by femtotrader** [comment] 2017-07-27 11:01
You should have a look at #98

**Comment by hmz123** [comment] 2017-07-27 15:07
thanks @femtotrader

**Comment by gbeced** [comment] 2017-08-04 00:59
Duplicate of https://github.com/gbeced/pyalgotrade/issues/98

**Closed by gbeced** 2017-08-04 00:59 UTC
